#version 310 es

layout(local_size_x = 64) in;

layout(std430, binding = 0) readonly buffer A {
    float a[];
};

layout(std430, binding = 1) readonly buffer B {
    float b[];
};

layout(std430, binding = 2) writeonly buffer C {
    float c[];
};

layout(std140, binding = 3) uniform Params {
    uint count;
};

void main()
{
    uint i = gl_WorkGroupID.x * gl_WorkGroupSize.x + gl_LocalInvocationIndex;
    if (i < count)
        c[i] = a[i] + b[i];
}
