/* AUTO-GENERATED from picoscript_lang.py -- do not edit by hand. */
#ifndef PICO_HOOKS_H
#define PICO_HOOKS_H

#define PV_HOST_HOOK_BASE  0x7000
#define PV_EXT_HOST_HOOK_BASE 0x6000
#define PV_NET_STATUS_BASE 0x8000
#define PV_NET_HEADER_BASE 0x9000
#define PV_NET_BODY_MARKER 0xB000
#define PV_NET_CLOSE_MARKER 0xC000

/* Module container (INV-23): wire format shared with pico_module.py / picovm.js. */
#define PV_MODULE_MAGIC 0x50534331
#define PV_MODULE_ABI_VERSION 1
#define PV_HOOK_TABLE_VERSION 0x968CCEF1

#define PV_HOOK_KERNEL_WAITIRQ                   0x01
#define PV_HOOK_KERNEL_WAITSWIRQ                 0x02
#define PV_HOOK_KERNEL_FIRESWIRQ                 0x03
#define PV_HOOK_KERNEL_PROFILESTART              0x04
#define PV_HOOK_KERNEL_PROFILEEND                0x05
#define PV_HOOK_KERNEL_TRACEPOINT                0x06
#define PV_HOOK_REQ_SEQ                          0x07
#define PV_HOOK_REQ_PRINCIPAL                    0x08
#define PV_HOOK_REQ_METHOD                       0x09
#define PV_HOOK_REQ_PATH                         0x0A
#define PV_HOOK_REQ_HEADER                       0x0B
#define PV_HOOK_REQ_BODYMODE                     0x0C
#define PV_HOOK_REQ_BODYCOUNT                    0x0D
#define PV_HOOK_REQ_BODYSPAN                     0x0E
#define PV_HOOK_QUEUE_DEQUEUE                    0x10
#define PV_HOOK_QUEUE_ENQUEUE                    0x11
#define PV_HOOK_QUEUE_DEPTH                      0x12
#define PV_HOOK_QUEUE_DEQUEUEBATCH               0x13
#define PV_HOOK_QUEUE_ENQUEUEBATCH               0x14
#define PV_HOOK_RESP_STATUS                      0x15
#define PV_HOOK_RESP_HEADER                      0x16
#define PV_HOOK_RESP_WRITE                       0x17
#define PV_HOOK_RESP_TRAILER                     0x18
#define PV_HOOK_RESP_SEAL                        0x19
#define PV_HOOK_RESP_END                         0x1A
#define PV_HOOK_RESP_RESPOND                     0x1B
#define PV_HOOK_RESP_FLUSH                       0x1C
#define PV_HOOK_RESP_CONTINUE                    0x1D
#define PV_HOOK_RESP_ENDSTREAM                   0x1E
#define PV_HOOK_RESP_UPGRADE                     0x1F
#define PV_HOOK_RANDOM_U32                       0x20
#define PV_HOOK_UTF8WRITER_NEW                   0x21
#define PV_HOOK_UTF8WRITER_BYTE                  0x22
#define PV_HOOK_UTF8WRITER_INT                   0x23
#define PV_HOOK_UTF8WRITER_SPAN                  0x24
#define PV_HOOK_UTF8WRITER_TOSPAN                0x25
#define PV_HOOK_UTF8WRITER_LEN                   0x26
#define PV_HOOK_UTF8WRITER_RESET                 0x27
#define PV_HOOK_UTF8READER_NEW                   0x28
#define PV_HOOK_UTF8READER_PEEK                  0x29
#define PV_HOOK_UTF8READER_NEXT                  0x2A
#define PV_HOOK_UTF8READER_INT                   0x2B
#define PV_HOOK_UTF8READER_SKIPWS                0x2C
#define PV_HOOK_UTF8READER_EOF                   0x2D
#define PV_HOOK_UTF8READER_POS                   0x2E
#define PV_HOOK_UTF8READER_MATCH                 0x2F
#define PV_HOOK_MEMORY_ARENAINIT                 0x30
#define PV_HOOK_MEMORY_ARENAALLOC                0x31
#define PV_HOOK_MEMORY_ARENARESET                0x32
#define PV_HOOK_MEMORY_ARENASTATS                0x33
#define PV_HOOK_MEMORY_PEEK                      0x34
#define PV_HOOK_MEMORY_POKE                      0x35
#define PV_HOOK_MEMORY_SET                       0x36
#define PV_HOOK_MEMORY_GET                       0x37
#define PV_HOOK_RESP_ABORT                       0x38
#define PV_HOOK_RESP_EARLYHINTS                  0x39
#define PV_HOOK_BITS_AND                         0x3A
#define PV_HOOK_BITS_OR                          0x3B
#define PV_HOOK_BITS_XOR                         0x3C
#define PV_HOOK_BITS_SHL                         0x3D
#define PV_HOOK_BITS_SHR                         0x3E
#define PV_HOOK_BITS_SAR                         0x3F
#define PV_HOOK_SPAN_MAKE                        0x40
#define PV_HOOK_SPAN_SLICE                       0x41
#define PV_HOOK_SPAN_MATERIALIZE                 0x42
#define PV_HOOK_SPAN_LEN                         0x43
#define PV_HOOK_SPAN_GET                         0x44
#define PV_HOOK_JSON_BEGINOBJECT                 0x45
#define PV_HOOK_JSON_ENDOBJECT                   0x46
#define PV_HOOK_JSON_BEGINARRAY                  0x47
#define PV_HOOK_JSON_ENDARRAY                    0x48
#define PV_HOOK_JSON_KEY                         0x49
#define PV_HOOK_JSON_STR                         0x4A
#define PV_HOOK_JSON_INT                         0x4B
#define PV_HOOK_JSON_BOOL                        0x4C
#define PV_HOOK_JSON_NULL                        0x4D
#define PV_HOOK_JSON_RAW                         0x4E
#define PV_HOOK_BITS_NOT                         0x4F
#define PV_HOOK_DESCRIPTOR_MAKE                  0x50
#define PV_HOOK_DESCRIPTOR_SETFLAGS              0x51
#define PV_HOOK_DESCRIPTOR_GETPTR                0x52
#define PV_HOOK_DESCRIPTOR_GETLEN                0x53
#define PV_HOOK_DESCRIPTOR_GETFLAGS              0x54
#define PV_HOOK_DESCRIPTOR_COPYBATCH             0x55
#define PV_HOOK_DOT8_LEN                         0x56
#define PV_HOOK_DOT8_OF                          0x57
#define PV_HOOK_LEASE_ACQUIRE                    0x58
#define PV_HOOK_LEASE_RELEASE                    0x59
#define PV_HOOK_LEASE_VALIDATE                   0x5A
#define PV_HOOK_LEASE_CACHEDVALIDATE             0x5B
#define PV_HOOK_LEASE_GETSPAN                    0x5C
#define PV_HOOK_LEASE_GETTYPEHINT                0x5D
#define PV_HOOK_STATUS_LAST                      0x5E
#define PV_HOOK_MEMORY_SETCONST                  0x5F
#define PV_HOOK_STORAGE_GETSCHEMAFORPACK         0x60
#define PV_HOOK_STORAGE_SETSCHEMAFORPACK         0x61
#define PV_HOOK_STORAGE_ADDCARD                  0x62
#define PV_HOOK_STORAGE_UPDATECARD               0x63
#define PV_HOOK_STORAGE_DELETECARD               0x64
#define PV_HOOK_STORAGE_PATCHCARD                0x65
#define PV_HOOK_STORAGE_READCARD                 0x66
#define PV_HOOK_STORAGE_QUERYCARD                0x67
#define PV_HOOK_STORAGE_USEPACK                  0x68
#define PV_HOOK_STORAGE_EDITCARD                 0x69
#define PV_HOOK_STORAGE_GETFIELD                 0x6A
#define PV_HOOK_STORAGE_SETFIELD                 0x6B
#define PV_HOOK_STORAGE_SETFIELDSTR              0x6C
#define PV_HOOK_STORAGE_GETFIELDSTR              0x6D
#define PV_HOOK_STORAGE_QUERYRESULT              0x6E
#define PV_HOOK_STORAGE_READY                    0x6F
#define PV_HOOK_THREAD_YIELDCOUNTED              0x70
#define PV_HOOK_IO_WRITE                         0x71
#define PV_HOOK_IO_WRITEBYTE                     0x72
#define PV_HOOK_XML_OPEN                         0x73
#define PV_HOOK_XML_ATTRNAME                     0x74
#define PV_HOOK_XML_ATTRVALUE                    0x75
#define PV_HOOK_XML_OPENEND                      0x76
#define PV_HOOK_XML_TEXT                         0x77
#define PV_HOOK_XML_CLOSE                        0x78
#define PV_HOOK_XML_EMPTY                        0x79
#define PV_HOOK_TEMPLATE_COMPILE                 0x7A
#define PV_HOOK_TEMPLATE_RENDER                  0x7B
#define PV_HOOK_ARENA_MARK                       0x7C
#define PV_HOOK_ARENA_REWIND                     0x7D
#define PV_HOOK_ARENA_RESET                      0x7E
#define PV_HOOK_STRING_CONCAT                    0x80
#define PV_HOOK_STRING_LENGTH                    0x81
#define PV_HOOK_STRING_SUBSTRING                 0x82
#define PV_HOOK_STRING_INDEXOF                   0x83
#define PV_HOOK_STRING_REPLACE                   0x84
#define PV_HOOK_STRING_TOUPPER                   0x85
#define PV_HOOK_STRING_TOLOWER                   0x86
#define PV_HOOK_STRING_TRIM                      0x87
#define PV_HOOK_STRING_SPLIT                     0x88
#define PV_HOOK_STRING_JOIN                      0x89
#define PV_HOOK_STRING_STARTSWITH                0x8A
#define PV_HOOK_STRING_ENDSWITH                  0x8B
#define PV_HOOK_STRING_SETREPLACE                0x8C
#define PV_HOOK_STRING_EQ                        0x8D
#define PV_HOOK_NUMBER_PARSE                     0x90
#define PV_HOOK_NUMBER_TOSTRING                  0x91
#define PV_HOOK_NUMBER_TOHEX                     0x92
#define PV_HOOK_NUMBER_TOOCTAL                   0x93
#define PV_HOOK_NUMBER_TOBINARY                  0x94
#define PV_HOOK_NUMBER_ABS                       0x95
#define PV_HOOK_NUMBER_FLOOR                     0x96
#define PV_HOOK_NUMBER_CEILING                   0x97
#define PV_HOOK_NUMBER_ROUND                     0x98
#define PV_HOOK_NUMBER_MIN                       0x99
#define PV_HOOK_NUMBER_MAX                       0x9A
#define PV_HOOK_MATHS_SIN                        0xA0
#define PV_HOOK_MATHS_COS                        0xA1
#define PV_HOOK_MATHS_TAN                        0xA2
#define PV_HOOK_MATHS_SQRT                       0xA3
#define PV_HOOK_MATHS_POWER                      0xA4
#define PV_HOOK_MATHS_LOG                        0xA5
#define PV_HOOK_MATHS_LOG10                      0xA6
#define PV_HOOK_MATHS_EXP                        0xA7
#define PV_HOOK_MATHS_RANDOM                     0xA8
#define PV_HOOK_MATHS_RANDOMRANGE                0xA9
#define PV_HOOK_MATHS_CLAMP                      0xAA
#define PV_HOOK_MATHS_LERP                       0xAB
#define PV_HOOK_DATETIME_NOW                     0xB0
#define PV_HOOK_DATETIME_UTCNOW                  0xB1
#define PV_HOOK_DATETIME_PARSE                   0xB2
#define PV_HOOK_DATETIME_FORMAT                  0xB3
#define PV_HOOK_DATETIME_ADDSECONDS              0xB4
#define PV_HOOK_DATETIME_ADDMINUTES              0xB5
#define PV_HOOK_DATETIME_ADDHOURS                0xB6
#define PV_HOOK_DATETIME_ADDDAYS                 0xB7
#define PV_HOOK_DATETIME_GETDAYOFWEEK            0xB8
#define PV_HOOK_DATETIME_GETDAYOFYEAR            0xB9
#define PV_HOOK_DATETIME_UNIXTIMESTAMP           0xBA
#define PV_HOOK_DATETIME_DIFFDAYS                0xBB
#define PV_HOOK_DATETIME_YEAR                    0xBC
#define PV_HOOK_DATETIME_MONTH                   0xBD
#define PV_HOOK_DATETIME_DAY                     0xBE
#define PV_HOOK_LOCALE_GETCURRENTLOCALE          0xC0
#define PV_HOOK_LOCALE_SETLOCALE                 0xC1
#define PV_HOOK_LOCALE_FORMATCURRENCY            0xC2
#define PV_HOOK_LOCALE_FORMATNUMBER              0xC3
#define PV_HOOK_LOCALE_FORMATDATE                0xC4
#define PV_HOOK_LOCALE_FORMATTIME                0xC5
#define PV_HOOK_LOCALE_TRANSLATE                 0xC6
#define PV_HOOK_ENVIRONMENT_GETOSVERSION         0xD0
#define PV_HOOK_ENVIRONMENT_GETCPUCOUNT          0xD1
#define PV_HOOK_ENVIRONMENT_GETMEMORYTOTAL       0xD2
#define PV_HOOK_ENVIRONMENT_GETMEMORYFREE        0xD3
#define PV_HOOK_ENVIRONMENT_GETHOSTNAME          0xD4
#define PV_HOOK_ENVIRONMENT_GETTIMEZONE          0xD5
#define PV_HOOK_ENVIRONMENT_GETPROCESSID         0xD6
#define PV_HOOK_ENVIRONMENT_GETTHREADID          0xD7
#define PV_HOOK_ENVIRONMENT_GETELAPSEDTIME       0xD8
#define PV_HOOK_CONTEXT_GETVERB                  0xE0
#define PV_HOOK_CONTEXT_GETPATH                  0xE1
#define PV_HOOK_CONTEXT_GETHOST                  0xE2
#define PV_HOOK_CONTEXT_GETPORT                  0xE3
#define PV_HOOK_CONTEXT_GETREMOTEADDR            0xE4
#define PV_HOOK_CONTEXT_GETUSER                  0xE5
#define PV_HOOK_CONTEXT_GETPERMISSIONS           0xE6
#define PV_HOOK_CONTEXT_GETHEADERS               0xE7
#define PV_HOOK_CONTEXT_GETQUERYSTRING           0xE8
#define PV_HOOK_CONTEXT_GETBODY                  0xE9
#define PV_HOOK_CONTEXT_SETSCRATCHVALUE          0xEA
#define PV_HOOK_CONTEXT_GETSCRATCHVALUE          0xEB
#define PV_HOOK_CONTEXT_GETREQUESTID             0xEC
#define PV_HOOK_CONTEXT_GETCLIENTCERT            0xED
#define PV_HOOK_CONTEXT_GETTRACEID               0xEE
#define PV_HOOK_CRYPTO_SHA256                    0xF0
#define PV_HOOK_CRYPTO_SHA512                    0xF1
#define PV_HOOK_CRYPTO_BLAKE2B                   0xF2
#define PV_HOOK_CRYPTO_BLAKE3                    0xF3
#define PV_HOOK_CRYPTO_HMACSHA256                0xF4
#define PV_HOOK_CRYPTO_HMACSHA512                0xF5
#define PV_HOOK_CRYPTO_SIGN                      0xF6
#define PV_HOOK_CRYPTO_VERIFY                    0xF7
#define PV_HOOK_CRYPTO_ENCRYPT                   0xF8
#define PV_HOOK_CRYPTO_DECRYPT                   0xF9
#define PV_HOOK_CRYPTO_GENERATEKEYPAIR           0xFA
#define PV_HOOK_CRYPTO_DERIVEKEY                 0xFB
#define PV_HOOK_CRYPTO_RANDOMBYTES               0xFC
#define PV_HOOK_CRYPTO_MD5                       0xFD
#define PV_HOOK_CRYPTO_SHA1                      0xFE
#define PV_HOOK_COMPRESS_BROTLICOMPRESS          0x100
#define PV_HOOK_COMPRESS_BROTLIDECOMPRESS        0x101
#define PV_HOOK_COMPRESS_PICOCOMPRESS            0x102
#define PV_HOOK_COMPRESS_PICODECOMPRESS          0x103
#define PV_HOOK_COMPRESS_GZIPCOMPRESS            0x104
#define PV_HOOK_COMPRESS_GZIPDECOMPRESS          0x105
#define PV_HOOK_COMPRESS_DEFLATECOMPRESS         0x106
#define PV_HOOK_COMPRESS_DEFLATEDECOMPRESS       0x107
#define PV_HOOK_X509_FETCHCERTIFICATE            0x110
#define PV_HOOK_X509_STORECERTIFICATE            0x111
#define PV_HOOK_X509_GENERATECSR                 0x112
#define PV_HOOK_X509_GENERATEKEYPAIR             0x113
#define PV_HOOK_X509_VERIFYCERTCHAIN             0x114
#define PV_HOOK_X509_GETCERTINFO                 0x115
#define PV_HOOK_X509_ISCERTVALID                 0x116
#define PV_HOOK_X509_GETKEYHANDLE                0x117
#define PV_HOOK_AUTH_GETUSERCREDENTIALS          0x120
#define PV_HOOK_AUTH_VALIDATECREDENTIALS         0x121
#define PV_HOOK_AUTH_SWITCHUSERCONTEXT           0x122
#define PV_HOOK_AUTH_GETUSERPERMISSIONS          0x123
#define PV_HOOK_AUTH_REQUESTTOKEN                0x124
#define PV_HOOK_AUTH_GETTOKEN                    0x125
#define PV_HOOK_AUTH_VALIDATETOKEN               0x126
#define PV_HOOK_AUTH_SWITCHTOKENCONTEXT          0x127
#define PV_HOOK_AUTH_REFRESHTOKEN                0x128
#define PV_HOOK_AUTH_REVOKETOKEN                 0x129
#define PV_HOOK_HTTP_READHEADER                  0x130
#define PV_HOOK_HTTP_READBODY                    0x131
#define PV_HOOK_HTTP_GENERATEHEADERS             0x132
#define PV_HOOK_HTTP_GENERATERESPONSE            0x133
#define PV_HOOK_HTTP_PARSEQUERY                  0x134
#define PV_HOOK_HTTP_PARSEFORM                   0x135
#define PV_HOOK_HTTP_PARSEJSON                   0x136
#define PV_HOOK_HTTP_ENCODEJSON                  0x137
#define PV_HOOK_HTTP_REQUEST                     0x138
#define PV_HOOK_HTTP_RESPSTATUS                  0x139
#define PV_HOOK_HTTP_RESPHEADERS                 0x13A
#define PV_HOOK_HTTP_RESPBODY                    0x13B
#define PV_HOOK_HTML_CREATENODE                  0x140
#define PV_HOOK_HTML_ADDCHILDNODE                0x141
#define PV_HOOK_HTML_REMOVECHILDNODE             0x142
#define PV_HOOK_HTML_SETATTRIBUTE                0x143
#define PV_HOOK_HTML_GETATTRIBUTE                0x144
#define PV_HOOK_HTML_PARSETREE                   0x145
#define PV_HOOK_HTML_ENCODE                      0x146
#define PV_HOOK_HTML_DECODE                      0x147
#define PV_HOOK_HTML_SERIALIZE                   0x148
#define PV_HOOK_HTML_QUERYSELECTOR               0x149
#define PV_HOOK_GPIO_COUNT                       0x150
#define PV_HOOK_GPIO_SETDIR                      0x151
#define PV_HOOK_GPIO_GETDIR                      0x152
#define PV_HOOK_GPIO_SETPULL                     0x153
#define PV_HOOK_GPIO_GETPULL                     0x154
#define PV_HOOK_GPIO_WRITE                       0x155
#define PV_HOOK_GPIO_READ                        0x156
#define PV_HOOK_PACK_USE                         0x160
#define PV_HOOK_CARD_READ                        0x161
#define PV_HOOK_CARD_WRITE                       0x162
#define PV_HOOK_CARD_ADDRESS                     0x163
#define PV_HOOK_FIFO_OPEN                        0x164
#define PV_HOOK_FIFO_SEND                        0x165
#define PV_HOOK_FIFO_RECV                        0x166
#define PV_HOOK_FIFO_POLL                        0x167
#define PV_HOOK_DEVICE_OPEN                      0x168
#define PV_HOOK_DEVICE_CAPS                      0x169
#define PV_HOOK_DEVICE_CLOSE                     0x16A
#define PV_HOOK_DEVICE_STATUS                    0x16B
#define PV_HOOK_STREAM_OPEN                      0x170
#define PV_HOOK_STREAM_NEXT                      0x171
#define PV_HOOK_STREAM_SPAN                      0x172
#define PV_HOOK_STREAM_SUBMIT                    0x173
#define PV_HOOK_STREAM_RELEASE                   0x174
#define PV_HOOK_STREAM_CLOSE                     0x175
#define PV_HOOK_STREAM_SETSLICE                  0x176
#define PV_HOOK_STREAM_SLICE                     0x177
#define PV_HOOK_ASSERT_EQ                        0x178
#define PV_HOOK_ASSERT_TRUE                      0x179
#define PV_HOOK_ASSERT_COUNT                     0x17A
#define PV_HOOK_ASSERT_FAILED                    0x17B
#define PV_HOOK_ASSERT_RESET                     0x17C
#define PV_HOOK_EVENT_POST                       0x180
#define PV_HOOK_EVENT_NEXT                       0x181
#define PV_HOOK_EVENT_TYPE                       0x182
#define PV_HOOK_EVENT_TARGET                     0x183
#define PV_HOOK_EVENT_DATA                       0x184
#define PV_HOOK_EVENT_SETDATA                    0x185
#define PV_HOOK_EVENT_COUNT                      0x186
#define PV_HOOK_UI_WINDOW                        0x188
#define PV_HOOK_UI_PANEL                         0x189
#define PV_HOOK_UI_LABEL                         0x18A
#define PV_HOOK_UI_BUTTON                        0x18B
#define PV_HOOK_UI_TEXTBOX                       0x18C
#define PV_HOOK_UI_CHECKBOX                      0x18D
#define PV_HOOK_UI_POS                           0x18E
#define PV_HOOK_UI_SIZE                          0x18F
#define PV_HOOK_UI_SETTEXT                       0x190
#define PV_HOOK_UI_SETID                         0x191
#define PV_HOOK_UI_SETVALUE                      0x192
#define PV_HOOK_UI_SERIALIZE                     0x193
#define PV_HOOK_STORAGE_SETSLICE                 0x1A0
#define PV_HOOK_STORAGE_CARDLEN                  0x1A1
#define PV_HOOK_STORAGE_READSLICE                0x1A2
#define PV_HOOK_STORAGE_WRITESLICE               0x1A3
#define PV_HOOK_STORAGE_ISUSERPACK               0x1A4
#define PV_HOOK_REQ_SETSLICE                     0x1B0
#define PV_HOOK_REQ_BODYSLICE                    0x1B1
#define PV_HOOK_REQ_BODYLEN                      0x1B2
#define PV_HOOK_EVENT_SETSLICE                   0x1B3
#define PV_HOOK_EVENT_DATASLICE                  0x1B4
#define PV_HOOK_EVENT_DATALEN                    0x1B5
#define PV_HOOK_REQ_PARAM                        0x1B6
#define PV_HOOK_REQ_PARAMCOUNT                   0x1B7
#define PV_HOOK_QUERY_BUILDLOOKUPFILTER          0x1C0
#define PV_HOOK_QUERY_BUILDMANYTOMANYMAP         0x1C1
#define PV_HOOK_SEARCH_CLEAR                     0x1D0
#define PV_HOOK_SEARCH_UPSERTTEXT                0x1D1
#define PV_HOOK_SEARCH_DELETE                    0x1D2
#define PV_HOOK_SEARCH_INDEXPACK                 0x1D3
#define PV_HOOK_SEARCH_QUERYTEXT                 0x1D4
#define PV_HOOK_SEARCH_SETVECTOR                 0x1D5
#define PV_HOOK_SEARCH_QUERYHYBRID               0x1D6
#define PV_HOOK_SEARCH_RESULT                    0x1D7
#define PV_HOOK_SEARCH_SCORE                     0x1D8
#define PV_HOOK_SEARCH_PLAN                      0x1D9
#define PV_HOOK_SEARCH_SETSEMANTICWEIGHT         0x1DA
#define PV_HOOK_SEARCH_CONFIGURE                 0x1DB
#define PV_HOOK_SEARCH_COMPATIBLE                0x1DC
#define PV_HOOK_SEARCH_REBUILD                   0x1DD
#define PV_HOOK_SEARCH_SETFACET                  0x1DE
#define PV_HOOK_SEARCH_SETNUMBER                 0x1DF
#define PV_HOOK_TENSOR_SETSHAPE                  0x1E0
#define PV_HOOK_TENSOR_DOTI8                     0x1E1
#define PV_HOOK_TENSOR_MATVECI8                  0x1E2
#define PV_HOOK_TENSOR_ADDI32                    0x1E3
#define PV_HOOK_TENSOR_MULI32                    0x1E4
#define PV_HOOK_TENSOR_SCALEI32                  0x1E5
#define PV_HOOK_TENSOR_RELUI32                   0x1E6
#define PV_HOOK_TENSOR_RMSNORMI32                0x1E7
#define PV_HOOK_TENSOR_ROPEI32                   0x1E8
#define PV_HOOK_TENSOR_SOFTMAXI32                0x1E9
#define PV_HOOK_TENSOR_ARGMAXI32                 0x1EA
#define PV_HOOK_TENSOR_HASACCEL                  0x1EB
#define PV_HOOK_BITLINEAR_SETSHAPE               0x1F0
#define PV_HOOK_BITLINEAR_MATVECTERNARY          0x1F1
#define PV_HOOK_BITLINEAR_MATVECBITMAP           0x1F2
#define PV_HOOK_BITLINEAR_MATVECBASE3            0x1F3
#define PV_HOOK_BITLINEAR_HASFORMAT              0x1F4
#define PV_HOOK_SEARCH_CLEARFIELDS               0x200
#define PV_HOOK_SEARCH_FACETS                    0x201
#define PV_HOOK_SEARCH_FACETVALUE                0x202
#define PV_HOOK_SEARCH_FACETCOUNT                0x203
#define PV_HOOK_SEARCH_RANGE                     0x204
#define PV_HOOK_SEARCH_SAVE                      0x205
#define PV_HOOK_SEARCH_LOAD                      0x206
#define PV_HOOK_SEARCH_JOURNALUPSERT             0x207
#define PV_HOOK_SEARCH_JOURNALDELETE             0x208
#define PV_HOOK_SEARCH_JOURNALFACET              0x209
#define PV_HOOK_SEARCH_JOURNALNUMBER             0x20A
#define PV_HOOK_SEARCH_JOURNALREPLAY             0x20B
#define PV_HOOK_TOKENIZER_SETVOCAB               0x210
#define PV_HOOK_TOKENIZER_ENCODEBYTES            0x211
#define PV_HOOK_TOKENIZER_ENCODETRIE             0x212
#define PV_HOOK_TOKENIZER_DECODEBYTES            0x213
#define PV_HOOK_TOKENIZER_DECODETRIE             0x214
#define PV_HOOK_TOKENIZER_COUNT                  0x215
#define PV_HOOK_TOKENIZER_TOKEN                  0x216
#define PV_HOOK_MODEL_SETCONFIG                  0x220
#define PV_HOOK_MODEL_GETCONFIG                  0x221
#define PV_HOOK_MODEL_TENSORVIEW                 0x222
#define PV_HOOK_MODEL_TENSOROFFSET               0x223
#define PV_HOOK_MODEL_TENSORROWS                 0x224
#define PV_HOOK_MODEL_TENSORCOLS                 0x225
#define PV_HOOK_MODEL_TENSORFORMAT               0x226
#define PV_HOOK_MODEL_READTENSOR                 0x227
#define PV_HOOK_QUANT_ABSMAX                     0x228
#define PV_HOOK_QUANT_QUANTI8                    0x229
#define PV_HOOK_QUANT_DEQUANTI8                  0x22A
#define PV_HOOK_QUANT_APPLYSCALE                 0x22B
#define PV_HOOK_QUANT_GROUPSCALE                 0x22C
#define PV_HOOK_KV_SETSHAPE                      0x230
#define PV_HOOK_KV_WRITEK                        0x231
#define PV_HOOK_KV_WRITEV                        0x232
#define PV_HOOK_KV_READK                         0x233
#define PV_HOOK_KV_READV                         0x234
#define PV_HOOK_KV_LEN                           0x235
#define PV_HOOK_KV_CLEAR                         0x236
#define PV_HOOK_KV_SETHEAD                       0x237
#define PV_HOOK_KV_WRITEKH                       0x238
#define PV_HOOK_KV_WRITEVH                       0x239
#define PV_HOOK_KV_READKH                        0x23A
#define PV_HOOK_KV_READVH                        0x23B
#define PV_HOOK_SAMPLING_ARGMAX                  0x240
#define PV_HOOK_SAMPLING_TOPK                    0x241
#define PV_HOOK_SAMPLING_TEMPERATURE             0x242
#define PV_HOOK_SAMPLING_ARGMAXROWS              0x243
#define PV_HOOK_ATTENTION_SETSHAPE               0x250
#define PV_HOOK_ATTENTION_SCORES                 0x251
#define PV_HOOK_ATTENTION_MIX                    0x252
#define PV_HOOK_ATTENTION_ATTEND                 0x253
#define PV_HOOK_TEXTRENDER_RAW                   0x260
#define PV_HOOK_TEXTRENDER_TEXT                  0x261
#define PV_HOOK_TEXTRENDER_OPEN                  0x262
#define PV_HOOK_TEXTRENDER_ATTR                  0x263
#define PV_HOOK_TEXTRENDER_OPENEND               0x264
#define PV_HOOK_TEXTRENDER_CLOSE                 0x265
#define PV_HOOK_TEXTRENDER_EMPTY                 0x266
#define PV_HOOK_TEXTRENDER_HOLE                  0x267
#define PV_HOOK_TEXTRENDER_BR                    0x268
#define PV_HOOK_MODEL_READTENSORROW              0x270
#define PV_HOOK_MODEL_SETBLOCK                   0x271
#define PV_HOOK_MODEL_READTENSORBLOCK            0x272
#define PV_HOOK_MODEL_MATVECI8BLOCK              0x273
#define PV_HOOK_BITLINEAR_MATVECTERNARYBLOCK     0x274
#define PV_HOOK_BITLINEAR_MATVECBITMAPBLOCK      0x275
#define PV_HOOK_BITLINEAR_MATVECBASE3BLOCK       0x276
#define PV_HOOK_PROCESS_SELF                     0x280
#define PV_HOOK_PROCESS_PARENT                   0x281
#define PV_HOOK_PROCESS_SPAWN                    0x282
#define PV_HOOK_PROCESS_EXIT                     0x283
#define PV_HOOK_PROCESS_KILL                     0x284
#define PV_HOOK_PROCESS_STATUS                   0x285
#define PV_HOOK_PROCESS_WAIT                     0x286
#define PV_HOOK_PROCESS_ARGS                     0x287
#define PV_HOOK_ENV_GET                          0x288
#define PV_HOOK_ENV_SET                          0x289
#define PV_HOOK_ENV_COUNT                        0x28A
#define PV_HOOK_ENV_KEY                          0x28B
#define PV_HOOK_TIMER_AFTER                      0x290
#define PV_HOOK_TIMER_EVERY                      0x291
#define PV_HOOK_TIMER_CANCEL                     0x292
#define PV_HOOK_TIMER_ELAPSED                    0x293
#define PV_HOOK_SCHEDULER_TICK                   0x294
#define PV_HOOK_PRINCIPAL_CURRENT                0x2A0
#define PV_HOOK_PRINCIPAL_HASROLE                0x2A1
#define PV_HOOK_PRINCIPAL_CLAIMS                 0x2A2
#define PV_HOOK_CAPABILITY_HAS                   0x2A3
#define PV_HOOK_CAPABILITY_REQUEST               0x2A4
#define PV_HOOK_CAPABILITY_DROP                  0x2A5
#define PV_HOOK_SANDBOX_DENY                     0x2A6
#define PV_HOOK_ERROR_SETHANDLER                 0x2B0
#define PV_HOOK_ERROR_HASHANDLER                 0x2B1
#define PV_HOOK_ERROR_CODE                       0x2B2
#define PV_HOOK_ERROR_DETAIL                     0x2B3
#define PV_HOOK_ERROR_RESUME                     0x2B4
#define PV_HOOK_ERROR_CLEAR                      0x2B5
#define PV_HOOK_ERROR_RAISE                      0x2B6
#define PV_HOOK_ERROR_POPHANDLER                 0x2B7
#define PV_HOOK_CAPSULE_CALL                     0x2C0
#define PV_HOOK_CAPSULE_SCHEDULE                 0x2C1
#define PV_HOOK_CAPSULE_JUMP                     0x2C2
#define PV_HOOK_CAPSULE_LOADMODULE               0x2C3
#define PV_HOOK_CAPSULE_RUNMODULE                0x2C4
#define PV_HOOK_BASE64_ENCODE                    0x2D0
#define PV_HOOK_BASE64_DECODE                    0x2D1
#define PV_HOOK_BASE64_URLDECODE                 0x2D2
#define PV_HOOK_BASE64_URLENCODE                 0x2D3
#define PV_HOOK_NET_LISTEN                       0x2E0
#define PV_HOOK_NET_ACCEPT                       0x2E1
#define PV_HOOK_NET_READ                         0x2E2
#define PV_HOOK_NET_WRITE                        0x2E3
#define PV_HOOK_NET_SHUTDOWN                     0x2E4
#define PV_HOOK_NET_POOLSIZE                     0x2E5
#define PV_HOOK_NET_REGISTER                     0x2E6
#define PV_HOOK_LOG_WRITE                        0x2F0
#define PV_HOOK_LOG_COUNT                        0x2F1
#define PV_HOOK_LOG_LEVEL                        0x2F2
#define PV_HOOK_LOG_MESSAGE                      0x2F3
#define PV_HOOK_LOG_CLEAR                        0x2F4
#define PV_HOOK_DATA_LOOKUP                      0x300
#define PV_HOOK_DATA_FIELDNUM                    0x301
#define PV_HOOK_DATA_FIELDSTR                    0x302
#define PV_HOOK_ENCODING_ASCIIENCODE             0x310
#define PV_HOOK_ENCODING_ASCIIDECODE             0x311
#define PV_HOOK_ENCODING_UTF8ENCODE              0x312
#define PV_HOOK_ENCODING_UTF8DECODE              0x313
#define PV_HOOK_ENCODING_UTF16LEENCODE           0x314
#define PV_HOOK_ENCODING_UTF16LEDECODE           0x315
#define PV_HOOK_ENCODING_UTF16BEENCODE           0x316
#define PV_HOOK_ENCODING_UTF16BEDECODE           0x317
#define PV_HOOK_ENCODING_UTF7ENCODE              0x318
#define PV_HOOK_ENCODING_UTF7DECODE              0x319
#define PV_HOOK_ENCODING_HEXENCODE               0x31A
#define PV_HOOK_ENCODING_HEXDECODE               0x31B
#define PV_HOOK_MAP_NEW                          0x320
#define PV_HOOK_MAP_FREE                         0x321
#define PV_HOOK_MAP_CLEAR                        0x322
#define PV_HOOK_MAP_COUNT                        0x323
#define PV_HOOK_MAP_HASH                         0x324
#define PV_HOOK_MAP_PUTII                        0x325
#define PV_HOOK_MAP_GETII                        0x326
#define PV_HOOK_MAP_HASI                         0x327
#define PV_HOOK_MAP_DELI                         0x328
#define PV_HOOK_MAP_PUTIS                        0x329
#define PV_HOOK_MAP_GETIS                        0x32A
#define PV_HOOK_MAP_PUTNULLI                     0x32B
#define PV_HOOK_MAP_ISNULLI                      0x32C
#define PV_HOOK_MAP_PUTSI                        0x32D
#define PV_HOOK_MAP_GETSI                        0x32E
#define PV_HOOK_MAP_HASS                         0x32F
#define PV_HOOK_MAP_DELS                         0x330
#define PV_HOOK_MAP_PUTSS                        0x331
#define PV_HOOK_MAP_GETSS                        0x332
#define PV_HOOK_MAP_PUTNULLS                     0x333
#define PV_HOOK_MAP_ISNULLS                      0x334
#define PV_HOOK_MAP_KEYAT                        0x335
#define PV_HOOK_MAP_KEYSPANAT                    0x336
#define PV_HOOK_MAP_VALAT                        0x337
#define PV_HOOK_MAP_VALSPANAT                    0x338
#define PV_HOOK_MAP_VALISSPAN                    0x339
#define PV_HOOK_MAP_USE                          0x33A
#define PV_HOOK_JSON_PARSE                       0x340
#define PV_HOOK_BINARY_PARSECARD                 0x341
#define PV_HOOK_BINARY_SERIALIZECARD             0x342
#define PV_HOOK_BINARY_PARSEENTITY               0x343
#define PV_HOOK_BINARY_SERIALIZEENTITY           0x344
#define PV_HOOK_BINARY_SETKEY                    0x345
#define PV_HOOK_BINARY_VERIFY                    0x346
#define PV_HOOK_DECIMAL_PARSE                    0x350
#define PV_HOOK_DECIMAL_TOSTRING                 0x351
#define PV_HOOK_DECIMAL_ADD                      0x352
#define PV_HOOK_DECIMAL_SUB                      0x353
#define PV_HOOK_DECIMAL_MUL                      0x354
#define PV_HOOK_DECIMAL_DIV                      0x355
#define PV_HOOK_DECIMAL_COMPARE                  0x356
#define PV_HOOK_DECIMAL_TOINT                    0x357

/* Highest defined host-hook code. The compiler never emits a code above
 * this, so pv_default_host uses it to tell a defined-but-unbound host-
 * fillable primitive (INV-18 default: 0 / NOT_FOUND, mirroring
 * picoscript_vm.py / picovm.js) from a genuinely unknown hook id in
 * malformed bytecode, which fails closed (PV_FAULT_BAD_HOOK). */
#define PV_HOOK_CODE_MAX 0x357

#endif
