#pragma once

#include "types.h"

/* Generated by tools/v3d_shaders/mesa_v3d_wrap.exe on 2026-06-16.
 * Uniform layouts:
 *   vector_add: u64 a_addr, u64 b_addr, u64 c_addr
 *   relu:       u64 a_addr, u64 b_addr
 *
 * Current kernels operate on element 0 only. They are for hardware bring-up and
 * verification, not throughput.
 */

#define V3D_TINY_VECTOR_ADD_QPU_WORDS 14U
#define V3D_TINY_RELU_QPU_WORDS       11U

static const u64 v3d_tiny_vector_add_qpu[V3D_TINY_VECTOR_ADD_QPU_WORDS] = {
    0x38403186bb03f000ULL,
    0x39c0318c3803f000ULL,
    0x38603186bb03f000ULL,
    0x39c0318c3803f000ULL,
    0x38403186bb03f000ULL,
    0x38813186bb03f000ULL,
    0x38817186bb03f000ULL,
    0x382021860503f105ULL,
    0x382032c6bb183000ULL,
    0x39c0318c3803f000ULL,
    0x38002187bb03f00fULL,
    0x38203186bb03f000ULL,
    0x38003186bb03f000ULL,
    0x38003186bb03f000ULL,
};

static const u64 v3d_tiny_relu_qpu[V3D_TINY_RELU_QPU_WORDS] = {
    0x38603186bb03f000ULL,
    0x39c0318c3803f000ULL,
    0x38403186bb03f000ULL,
    0x38813186bb03f000ULL,
    0x38201146bb118000ULL,
    0x382032c6bb143000ULL,
    0x39c0318c3803f000ULL,
    0x38002186bb03f00fULL,
    0x38203186bb03f000ULL,
    0x38003186bb03f000ULL,
    0x38003186bb03f000ULL,
};
